name: readorsee
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - cffi=1.14.0=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1e=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pycparser=2.20=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.7=h191fe78_0_cpython
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - setuptools=46.1.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - alabaster==0.7.12
    - allennlp==0.9.0
    - attrs==19.3.0
    - babel==2.8.0
    - blis==0.2.4
    - boto3==1.12.28
    - botocore==1.15.28
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - conllu==1.3.1
    - cymem==2.0.3
    - decorator==4.4.2
    - docutils==0.15.2
    - editdistance==0.5.3
    - filelock==3.0.12
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.7
    - gensim==3.8.1
    - gevent==1.4.0
    - google-api-core==1.16.0
    - google-auth==1.11.3
    - google-cloud-core==1.3.0
    - google-cloud-storage==1.26.0
    - google-resumable-media==0.5.0
    - googleapis-common-protos==1.51.0
    - greenlet==0.4.15
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.8.0
    - imagesize==1.2.0
    - importlib-metadata==1.5.0
    - itsdangerous==1.1.0
    - jinja2==2.11.1
    - jmespath==0.9.5
    - joblib==0.14.1
    - jsonnet==0.15.0
    - jsonpickle==1.3
    - liwc==0.5.0
    - markupsafe==1.1.1
    - more-itertools==8.2.0
    - murmurhash==1.0.2
    - networkx==2.4
    - nltk==3.4.5
    - numpydoc==0.9.2
    - overrides==2.8.0
    - packaging==20.3
    - parsimonious==0.8.1
    - plac==0.9.6
    - pluggy==0.13.1
    - preshed==2.0.1
    - protobuf==3.11.3
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.6.1
    - pytest==5.4.1
    - python-dotenv==0.12.0
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pywavelets==1.1.1
    - regex==2020.2.20
    - requests==2.23.0
    - responses==0.10.12
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - smart-open==1.10.0
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==2.4.4
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlparse==0.3.1
    - srsly==1.0.2
    - tensorboardx==2.0
    - thinc==7.0.8
    - tokenizers==0.5.2
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.43.0
    - transformers==2.6.0
    - unidecode==1.1.1
    - urllib3==1.25.8
    - wasabi==0.6.0
    - wcwidth==0.1.9
    - werkzeug==1.0.0
    - word2number==1.1
    - zipp==3.1.0
